export const countries = [
  { label: "Afghanistan", flag: "🇦🇫", countryCode: "+93" },
  { label: "Albania", flag: "🇦🇱", countryCode: "+355" },
  { label: "Algeria", flag: "🇩🇿", countryCode: "+213" },
  { label: "American Samoa", flag: "🇦🇸", countryCode: "+1-684" },
  { label: "Andorra", flag: "🇦🇩", countryCode: "+376" },
  { label: "Angola", flag: "🇦🇴", countryCode: "+244" },
  { label: "Anguilla", flag: "🇦🇮", countryCode: "+1-264" },
  { label: "Antarctica", flag: "🇦🇶", countryCode: "+672" },
  { label: "Antigua and Barbuda", flag: "🇦🇬", countryCode: "+1-268" },
  { label: "Argentina", flag: "🇦🇷", countryCode: "+54" },
  { label: "Armenia", flag: "🇦🇲", countryCode: "+374" },
  { label: "Aruba", flag: "🇦🇼", countryCode: "+297" },
  { label: "Australia", flag: "🇦🇺", countryCode: "+61" },
  { label: "Austria", flag: "🇦🇹", countryCode: "+43" },
  { label: "Azerbaijan", flag: "🇦🇿", countryCode: "+994" },
  { label: "Bahamas", flag: "🇧🇸", countryCode: "+1-242" },
  { label: "Bahrain", flag: "🇧🇭", countryCode: "+973" },
  { label: "Bangladesh", flag: "🇧🇩", countryCode: "+880" },
  { label: "Barbados", flag: "🇧🇧", countryCode: "+1-246" },
  { label: "Belarus", flag: "🇧🇾", countryCode: "+375" },
  { label: "Belgium", flag: "🇧🇪", countryCode: "+32" },
  { label: "Belize", flag: "🇧🇿", countryCode: "+501" },
  { label: "Benin", flag: "🇧🇯", countryCode: "+229" },
  { label: "Bermuda", flag: "🇧🇲", countryCode: "+1-441" },
  { label: "Bhutan", flag: "🇧🇹", countryCode: "+975" },
  { label: "Bolivia", flag: "🇧🇴", countryCode: "+591" },
  { label: "Bosnia and Herzegovina", flag: "🇧🇦", countryCode: "+387" },
  { label: "Botswana", flag: "🇧🇼", countryCode: "+267" },
  { label: "Brazil", flag: "🇧🇷", countryCode: "+55" },
  { label: "Brunei Darussalam", flag: "🇧🇳", countryCode: "+673" },
  { label: "Bulgaria", flag: "🇧🇬", countryCode: "+359" },
  { label: "Burkina Faso", flag: "🇧🇫", countryCode: "+226" },
  { label: "Burundi", flag: "🇧🇮", countryCode: "+257" },
  { label: "Cambodia", flag: "🇰🇭", countryCode: "+855" },
  { label: "Cameroon", flag: "🇨🇲", countryCode: "+237" },
  { label: "Canada", flag: "🇨🇦", countryCode: "+1" },
  { label: "Cape Verde", flag: "🇨🇻", countryCode: "+238" },
  { label: "Cayman Islands", flag: "🇰🇾", countryCode: "+1-345" },
  { label: "Central African Republic", flag: "🇨🇫", countryCode: "+236" },
  { label: "Chad", flag: "🇹🇩", countryCode: "+235" },
  { label: "Chile", flag: "🇨🇱", countryCode: "+56" },
  { label: "China", flag: "🇨🇳", countryCode: "+86" },
  { label: "Colombia", flag: "🇨🇴", countryCode: "+57" },
  { label: "Comoros", flag: "🇰🇲", countryCode: "+269" },
  { label: "Congo", flag: "🇨🇬", countryCode: "+242" },
  { label: "Congo (DRC)", flag: "🇨🇩", countryCode: "+243" },
  { label: "Costa Rica", flag: "🇨🇷", countryCode: "+506" },
  { label: "Croatia", flag: "🇭🇷", countryCode: "+385" },
  { label: "Cuba", flag: "🇨🇺", countryCode: "+53" },
  { label: "Cyprus", flag: "🇨🇾", countryCode: "+357" },
  { label: "Czech Republic", flag: "🇨🇿", countryCode: "+420" },
  { label: "Denmark", flag: "🇩🇰", countryCode: "+45" },
  { label: "Djibouti", flag: "🇩🇯", countryCode: "+253" },
  { label: "Dominica", flag: "🇩🇲", countryCode: "+1-767" },
  { label: "Dominican Republic", flag: "🇩🇴", countryCode: "+1-809" },
  { label: "Ecuador", flag: "🇪🇨", countryCode: "+593" },
  { label: "Egypt", flag: "🇪🇬", countryCode: "+20" },
  { label: "El Salvador", flag: "🇸🇻", countryCode: "+503" },
  { label: "Equatorial Guinea", flag: "🇬🇶", countryCode: "+240" },
  { label: "Eritrea", flag: "🇪🇷", countryCode: "+291" },
  { label: "Estonia", flag: "🇪🇪", countryCode: "+372" },
  { label: "Eswatini", flag: "🇸🇿", countryCode: "+268" },
  { label: "Ethiopia", flag: "🇪🇹", countryCode: "+251" },
  { label: "Fiji", flag: "🇫🇯", countryCode: "+679" },
  { label: "Finland", flag: "🇫🇮", countryCode: "+358" },
  { label: "France", flag: "🇫🇷", countryCode: "+33" },
  { label: "French Guiana", flag: "🇬🇫", countryCode: "+594" },
  { label: "French Polynesia", flag: "🇵🇫", countryCode: "+689" },
  { label: "Gabon", flag: "🇬🇦", countryCode: "+241" },
  { label: "Gambia", flag: "🇬🇲", countryCode: "+220" },
  { label: "Georgia", flag: "🇬🇪", countryCode: "+995" },
  { label: "Germany", flag: "🇩🇪", countryCode: "+49" },
  { label: "Ghana", flag: "🇬🇭", countryCode: "+233" },
  { label: "Gibraltar", flag: "🇬🇮", countryCode: "+350" },
  { label: "Greece", flag: "🇬🇷", countryCode: "+30" },
  { label: "Greenland", flag: "🇬🇱", countryCode: "+299" },
  { label: "Grenada", flag: "🇬🇩", countryCode: "+1-473" },
  { label: "Guam", flag: "🇬🇺", countryCode: "+1-671" },
  { label: "Guatemala", flag: "🇬🇹", countryCode: "+502" },
  { label: "Guernsey", flag: "🇬🇬", countryCode: "+44" },
  { label: "Guinea", flag: "🇬🇳", countryCode: "+224" },
  { label: "Guinea-Bissau", flag: "🇬🇼", countryCode: "+245" },
  { label: "Guyana", flag: "🇬🇾", countryCode: "+592" },
  { label: "Haiti", flag: "🇭🇹", countryCode: "+509" },
  { label: "Honduras", flag: "🇭🇳", countryCode: "+504" },
  { label: "Hong Kong", flag: "🇭🇰", countryCode: "+852" },
  { label: "Hungary", flag: "🇭🇺", countryCode: "+36" },
  { label: "Iceland", flag: "🇮🇸", countryCode: "+354" },
  { label: "India", flag: "🇮🇳", countryCode: "+91" },
  { label: "Indonesia", flag: "🇮🇩", countryCode: "+62" },
  { label: "Iran", flag: "🇮🇷", countryCode: "+98" },
  { label: "Iraq", flag: "🇮🇶", countryCode: "+964" },
  { label: "Ireland", flag: "🇮🇪", countryCode: "+353" },
  { label: "Israel", flag: "🇮🇱", countryCode: "+972" },
  { label: "Italy", flag: "🇮🇹", countryCode: "+39" },
  { label: "Jamaica", flag: "🇯🇲", countryCode: "+1-876" },
  { label: "Japan", flag: "🇯🇵", countryCode: "+81" },
  { label: "Jersey", flag: "🇯🇪", countryCode: "+44" },
  { label: "Jordan", flag: "🇯🇴", countryCode: "+962" },
  { label: "Kazakhstan", flag: "🇰🇿", countryCode: "+7" },
  { label: "Kenya", flag: "🇰🇪", countryCode: "+254" },
  { label: "Kiribati", flag: "🇰🇮", countryCode: "+686" },
  { label: "North Korea", flag: "🇰🇵", countryCode: "+850" },
  { label: "South Korea", flag: "🇰🇷", countryCode: "+82" },
  { label: "Kuwait", flag: "🇰🇼", countryCode: "+965" },
  { label: "Kyrgyzstan", flag: "🇰🇬", countryCode: "+996" },
];
